# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(13, 13, 423, 575))
        self.frame.setStyleSheet("background-color: rgb(242, 242, 242);\n"
"border: 2px solid #707070;\n"
"border-radius: 40px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(112, 112, 112);\n"
"border: 0px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(14, 60, 391, 224))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #707070;\n"
"border-radius: 0px;")
        self.listWidget.setObjectName("listWidget")
        self.pushButton_e = QtWidgets.QPushButton(self.frame)
        self.pushButton_e.setGeometry(QtCore.QRect(140, 300, 134, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_e.setFont(font)
        self.pushButton_e.setStyleSheet("QPushButton{\n"
"background-color: rgb(39, 153, 243);\n"
"    color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"border-radius: 16px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 132, 208);\n"
"}")
        self.pushButton_e.setObjectName("pushButton_e")
        self.pushButton_b = QtWidgets.QPushButton(self.frame)
        self.pushButton_b.setGeometry(QtCore.QRect(16, 480, 134, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_b.setFont(font)
        self.pushButton_b.setStyleSheet("QPushButton{\n"
"background-color: rgb(39, 153, 243);\n"
"    color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"border-radius: 16px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 132, 208);\n"
"}")
        self.pushButton_b.setObjectName("pushButton_b")
        self.pushButton_a = QtWidgets.QPushButton(self.frame)
        self.pushButton_a.setGeometry(QtCore.QRect(270, 480, 134, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_a.setFont(font)
        self.pushButton_a.setStyleSheet("QPushButton{\n"
"background-color: rgb(39, 153, 243);\n"
"    color: rgb(255, 255, 255);\n"
"border: 0px;\n"
"border-radius: 16px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(33, 132, 208);\n"
"}")
        self.pushButton_a.setObjectName("pushButton_a")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 350, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(112, 112, 112);\n"
"border: 0px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(14, 390, 391, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid #707070;\n"
"border-radius: 0px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_folder = QtWidgets.QLabel(self.frame)
        self.label_folder.setGeometry(QtCore.QRect(14, 430, 391, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_folder.setFont(font)
        self.label_folder.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"    \n"
"border: 1px solid #707070;\n"
"\n"
"}")
        self.label_folder.setObjectName("label_folder")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(376, 529, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(0, 120, 212);\n"
"border: 2px solid #707070;\n"
"border-radius: 15px;")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dev Modder"))
        self.pushButton_e.setText(_translate("MainWindow", "Enable"))
        self.pushButton_b.setText(_translate("MainWindow", "Browse"))
        self.pushButton_a.setText(_translate("MainWindow", "Add widget"))
        self.label_2.setText(_translate("MainWindow", "Add Custom Widget"))
        self.lineEdit.setText(_translate("MainWindow", "Enter the name of your widget"))
        self.label_folder.setText(_translate("MainWindow", "Your selected folder"))
        self.pushButton_4.setText(_translate("MainWindow", "X"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
