# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'balls.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime,Qt
import pyaudio
import numpy as np
import webbrowser
import os

CHUNK = 4096 # number of data points to read at a time
RATE = 44100 # time resolution of the recording device (Hz)
MAX_VALUE=2**16
BAR=100
class Ui_Form_Vi(object):
    def __init__(self, Form):
        self.Form=Form
        Form.setObjectName("Form")
        Form.resize(620, 175)
        self.tempdict={}
        self.mainindex=0
        
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint  |QtCore.Qt.WindowStaysOnBottomHint| QtCore.Qt.Tool)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
    

        np.set_printoptions(suppress=True) # don't use scientific notation
        self.style_dict={}
        self.reader()
        self.Form.move(int(self.style_dict["defaultx"]),int(self.style_dict["defaulty"]))

        self.p=pyaudio.PyAudio() # start the PyAudio class


        for i in range(self.p.get_device_count()):
                self.tempdict=self.p.get_device_info_by_index(i)
                print(self.tempdict)
                if "Stereo Mix" in self.tempdict["name"]:
                        self.mainindex=self.tempdict["index"]
                        break
        self.stream=self.p.open(format=pyaudio.paInt16,channels=1,rate=RATE,input=True,input_device_index = self.mainindex,
              frames_per_buffer=CHUNK) #uses default input device


        self.label_0 = QtWidgets.QLabel(Form)
        
        # self.label_0.setGeometry(QtCore.QRect(10, 10, 14, 14))
        self.label_0.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius: 7px;")
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")
        self.label_1 = QtWidgets.QLabel(Form)
        

        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
       

        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        

        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
    

        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        

        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        

        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(Form)
        

        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(Form)
        

        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(Form)
        

        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Form)
        

        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(Form)
      

        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Form)
        

        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(Form)
        

        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(Form)
        

        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_25 = QtWidgets.QLabel(Form)
        

        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_15 = QtWidgets.QLabel(Form)
        

        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(Form)
        

        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(Form)
      

        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(Form)
      

        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_22 = QtWidgets.QLabel(Form)
        

        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_28 = QtWidgets.QLabel(Form)
        

        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_20 = QtWidgets.QLabel(Form)
        

        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_19 = QtWidgets.QLabel(Form)
        

        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_27 = QtWidgets.QLabel(Form)
        

        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_18 = QtWidgets.QLabel(Form)
        

        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_24 = QtWidgets.QLabel(Form)
        

        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(Form)
        

        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_29 = QtWidgets.QLabel(Form)
        

        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_16 = QtWidgets.QLabel(Form)
        

        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.original()


        self.combo = QtWidgets.QComboBox(Form)
        self.combo.setGeometry(QtCore.QRect(260, 30, 91, 22))
        self.combo.addItem("Customize")
        self.combo.addItem("Refresh")
        self.combo.setItemData(0,"Customize")
        self.combo.setItemData(1,"Refresh")
        self.combo.activated.connect(lambda: self.itemselected())

        self.timer = QTimer(Form) 
  
        # adding action to timer 
        self.timer.timeout.connect(self.updater) 
  
        # update the timer every second 
        self.timer.start(100)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


    def original(self):
        
        for i in range(0,30):
            getattr(self,"label_%d"%i).setStyleSheet(self.style_dict['basecolor']+"border-radius: 7px;")
            getattr(self,"label_%d"%i).setGeometry(QtCore.QRect(10+i*20, 150, 14, 14))

        

    def reader(self):
        f=open("Widgets\\Visualizer\\visual.ini","r")
        for line in f:
                key,value= line.split("|")
                if value[-1]=="\n":
                        self.style_dict[key]=value[0:-1]
                else:
                        self.style_dict[key]=value
        # print(self.style_dict)

    def itemselected(self):
        print(self.combo.currentData())
        if self.combo.currentData()=="Customize":
            print(f"{os.getcwd()}\\Widgets\\Visualizer\\visual.ini")
            # os.system(f"notepad {os.getcwd()}\\clock.ini ")
            webbrowser.open(f"{os.getcwd()}\\Widgets\\Visualizer\\visual.ini")

        if self.combo.currentData()=="Refresh":
            self.reader()
            self.original()
            self.Form.move(int(self.style_dict["defaultx"]),int(self.style_dict["defaulty"]))
            if self.style_dict["clickthrough"]=="yes":
                    self.Form.setWindowFlags(QtCore.Qt.FramelessWindowHint  |QtCore.Qt.WindowStaysOnBottomHint | QtCore.Qt.WindowTransparentForInput | QtCore.Qt.Tool)
                    self.Form.show()
            elif self.style_dict["clickthrough"]=="no":
                    self.Form.setWindowFlags(QtCore.Qt.FramelessWindowHint  |QtCore.Qt.WindowStaysOnBottomHint | QtCore.Qt.Tool )
                    self.Form.show()

            

            

    def updater(self):
        global CHUNK,RATE,MAX_VALUE
        data = np.fromstring(self.stream.read(CHUNK),dtype=np.int16)
        data = data * np.hanning(len(data)) # smooth the FFT by windowing data
        fft = abs(np.fft.fft(data).real)
        fft = fft[:int(len(fft)/2)] # keep only first half
        freq = np.fft.fftfreq(CHUNK,1.0/RATE)
        freq = freq[:int(len(freq)/2)] # keep only first half
        freqPeak = freq[np.where(fft==np.max(fft))[0][0]]+1
        dataR = data[1::2]
        peakR = np.abs(np.max(dataR)-np.min(dataR))/MAX_VALUE
        self.original()

        if freqPeak>250 and freqPeak<300:
                self.label_10.setStyleSheet(self.style_dict["submid"]+"border-radius: 7px;")
                self.label_10.setGeometry(QtCore.QRect(210, int(150-(peakR*BAR)), 14, 14))

        if freqPeak>300 and freqPeak<350:
                self.label_11.setStyleSheet(self.style_dict["submid"]+"border-radius: 7px;")
                self.label_11.setGeometry(QtCore.QRect(230, int(150-(peakR*BAR)), 14, 14))
        
        if freqPeak>350 and freqPeak<400:
                self.label_12.setStyleSheet(self.style_dict["submid"]+"border-radius: 7px;")
                self.label_12.setGeometry(QtCore.QRect(250, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>400 and freqPeak<450:
                self.label_13.setStyleSheet(self.style_dict["submid"]+"border-radius: 7px;")
                self.label_13.setGeometry(QtCore.QRect(270, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>450 and freqPeak<500:
                self.label_14.setStyleSheet(self.style_dict["submid"]+"border-radius: 7px;")
                self.label_14.setGeometry(QtCore.QRect(290, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>500 and freqPeak<600:
                self.label_15.setStyleSheet(self.style_dict["highmid"]+"border-radius: 7px;")
                self.label_15.setGeometry(QtCore.QRect(310, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>600 and freqPeak<700:
                self.label_16.setStyleSheet(self.style_dict["highmid"]+"border-radius: 7px;")
                self.label_16.setGeometry(QtCore.QRect(330, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>700 and freqPeak<800:
                self.label_17.setStyleSheet(self.style_dict["highmid"]+"border-radius: 7px;")
                self.label_17.setGeometry(QtCore.QRect(350, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>800 and freqPeak<900:
                self.label_18.setStyleSheet(self.style_dict["highmid"]+"border-radius: 7px;")
                self.label_18.setGeometry(QtCore.QRect(370, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>900 and freqPeak<1000:
                self.label_19.setStyleSheet(self.style_dict["highmid"]+"border-radius: 7px;")
                self.label_19.setGeometry(QtCore.QRect(390, int(150-(peakR*BAR)), 14, 14))
       
        if freqPeak>150 and freqPeak<160:
                self.label_0.setStyleSheet(self.style_dict["subbass"]+"border-radius: 7px;")
                self.label_0.setGeometry(QtCore.QRect(10, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>160 and freqPeak<170:
                self.label_1.setStyleSheet(self.style_dict["subbass"]+"border-radius: 7px;")
                self.label_1.setGeometry(QtCore.QRect(30, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>170 and freqPeak<180:
                self.label_2.setStyleSheet(self.style_dict["subbass"]+"border-radius: 7px;")
                self.label_2.setGeometry(QtCore.QRect(50, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>180 and freqPeak<190:
                self.label_3.setStyleSheet(self.style_dict["highbass"]+"border-radius: 7px;")
                self.label_3.setGeometry(QtCore.QRect(70, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>190 and freqPeak<200:
                self.label_4.setStyleSheet(self.style_dict["highbass"]+"border-radius: 7px;") 
                self.label_4.setGeometry(QtCore.QRect(90, int(150-(peakR*BAR)), 14, 14))     
        if freqPeak>200 and freqPeak<210:
                self.label_5.setStyleSheet(self.style_dict["highbass"]+"border-radius: 7px;")
                self.label_5.setGeometry(QtCore.QRect(110, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>210 and freqPeak<220:
                self.label_6.setStyleSheet(self.style_dict["lowbass"]+"border-radius: 7px;")
                self.label_6.setGeometry(QtCore.QRect(130, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>220 and freqPeak<230:
                self.label_7.setStyleSheet(self.style_dict["lowbass"]+"border-radius: 7px;")
                self.label_7.setGeometry(QtCore.QRect(150, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>230 and freqPeak<240:
                self.label_8.setStyleSheet(self.style_dict["lowbass"]+"border-radius: 7px;")
                self.label_8.setGeometry(QtCore.QRect(170, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>240 and freqPeak<250:
                self.label_9.setStyleSheet(self.style_dict["lowbass"]+"border-radius: 7px;")
                self.label_9.setGeometry(QtCore.QRect(190, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>1000 and freqPeak<1300:
                self.label_20.setStyleSheet(self.style_dict["lowmid"]+"border-radius: 7px;")
                self.label_20.setGeometry(QtCore.QRect(410, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>1300 and freqPeak<1600:
                self.label_21.setStyleSheet(self.style_dict["lowmid"]+"border-radius: 7px;")
                self.label_21.setGeometry(QtCore.QRect(430, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>1600 and freqPeak<2000:
                self.label_22.setStyleSheet(self.style_dict["lowmid"]+"border-radius: 7px;")
                self.label_22.setGeometry(QtCore.QRect(450, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>2000 and freqPeak<3000:
                self.label_23.setStyleSheet(self.style_dict["lowmid"]+"border-radius: 7px;")
                self.label_23.setGeometry(QtCore.QRect(470, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>3000 and freqPeak<4000:
                self.label_24.setStyleSheet(self.style_dict["lowmid"]+"border-radius: 7px;")
                self.label_24.setGeometry(QtCore.QRect(490, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>4000 and freqPeak<5000:
                self.label_25.setStyleSheet(self.style_dict["treble"]+"border-radius: 7px;")
                self.label_25.setGeometry(QtCore.QRect(510, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>5000 and freqPeak<5500:
                self.label_26.setStyleSheet(self.style_dict["treble"]+"border-radius: 7px;")
                self.label_26.setGeometry(QtCore.QRect(530, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>5500 and freqPeak<6000:
                self.label_27.setStyleSheet(self.style_dict["treble"]+"border-radius: 7px;")
                self.label_27.setGeometry(QtCore.QRect(550, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>6000 and freqPeak<8000:
                self.label_28.setStyleSheet(self.style_dict["hightreble"]+"border-radius: 7px;")
                self.label_28.setGeometry(QtCore.QRect(570, int(150-(peakR*BAR)), 14, 14))
        if freqPeak>8000 and freqPeak<10000:
                self.label_29.setStyleSheet(self.style_dict["hightreble"]+"border-radius: 7px;")
                self.label_29.setGeometry(QtCore.QRect(590, int(150-(peakR*BAR)), 14, 14))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form_Vi(Form)
#     Form.show()
#     sys.exit(app.exec_())
